name: camera_example
description: Demonstrates how to use the camera plugin.
version: 1.0.0

publish_to: none

dependencies:
  flutter_better_camera:
    path: ../
  path_provider: 2.0.2
  video_player: 2.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
